# Generated by Django 2.2 on 2019-04-27 14:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190427_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_no',
            field=models.CharField(default='+7-499-555-55-55', max_length=255, verbose_name='Контактный телефон'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('СТ', 'Студент'), ('УЧ', 'Учитель')], default='СТ', max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 27, 14, 41, 32, 945372, tzinfo=utc), verbose_name='Дата рождения'),
        ),
    ]
