# Generated by Django 2.2 on 2019-04-27 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190427_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Дата рождения'),
        ),
    ]
