# Generated by Django 2.2 on 2019-04-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190427_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('СТ', 'Студент'), ('ПР', 'Преподаватель')], default='СТ', max_length=2, verbose_name='Роль пользователя'),
        ),
    ]
