# Generated by Django 2.2 on 2019-04-27 18:21

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190427_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[articles.models.validate_file_extension], verbose_name='Файл'),
        ),
    ]
