# Generated by Django 2.2 on 2019-05-08 18:26

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190427_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y%m%D/', validators=[articles.models.validate_file_extension], verbose_name='Файл'),
        ),
    ]
