# Generated by Django 2.2 on 2019-05-08 20:16

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190508_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents', validators=[articles.models.validate_file_extension], verbose_name='Файл'),
        ),
    ]
