# Generated by Django 2.2 on 2019-05-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_control', '0002_auto_20190517_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='tmp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
