# Generated by Django 2.2 on 2019-05-20 09:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='РК1', max_length=255, verbose_name='Название РК')),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('date_stop', models.DateTimeField(default=datetime.datetime(2019, 5, 23, 9, 32, 41, 7181, tzinfo=utc), verbose_name='Дата окончания')),
                ('disciple', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance_control.Disciple', verbose_name='Дисциплина')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Некоторый вопрос', max_length=255, verbose_name='Название вопроса')),
                ('body', models.TextField(default='Выберете правильный вариант ответа...', verbose_name='Содержание вопроса')),
                ('answer_true', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1, verbose_name='Вариант правильного ответа')),
                ('rk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questiontest.RK', verbose_name='Контрольные вопросы')),
            ],
        ),
    ]
