# Generated by Django 2.2 on 2019-05-20 11:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questiontest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rk',
            name='date_stop',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 23, 11, 25, 21, 4873, tzinfo=utc), verbose_name='Дата окончания'),
        ),
    ]
