# Generated by Django 2.2 on 2019-05-20 11:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questiontest', '0002_auto_20190520_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rk',
            name='date_stop',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 23, 11, 30, 29, 302918, tzinfo=utc), verbose_name='Дата окончания'),
        ),
    ]
