# Generated by Django 2.2 on 2019-05-20 12:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questiontest', '0004_auto_20190520_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rk',
            name='date_stop',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 23, 12, 33, 31, 579114, tzinfo=utc), verbose_name='Дата окончания'),
        ),
        migrations.CreateModel(
            name='RKResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(default='100%', max_length=5, verbose_name="Результат в '%'")),
                ('rk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questiontest.RK', verbose_name='РК')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
        ),
    ]
