# Generated by Django 2.2 on 2019-05-20 12:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questiontest', '0006_auto_20190520_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rk',
            name='date_stop',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 23, 12, 42, 20, 589501, tzinfo=utc), verbose_name='Дата окончания'),
        ),
    ]
