# Generated by Django 2.2 on 2019-05-20 14:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questiontest', '0007_auto_20190520_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='rkresult',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='rk',
            name='date_stop',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 23, 14, 48, 48, 511576, tzinfo=utc), verbose_name='Дата окончания'),
        ),
    ]
