# Generated by Django 2.2 on 2019-05-23 09:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questiontest', '0009_auto_20190520_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rk',
            name='date_stop',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 9, 32, 41, 37650, tzinfo=utc), verbose_name='Дата окончания'),
        ),
    ]
