# Generated by Django 2.2 on 2019-05-20 09:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ГТВ', 'Готово'), ('ОБР', 'Обработка')], default='ОБР', max_length=3, verbose_name='Статус заявки')),
                ('title', models.CharField(max_length=255, verbose_name='Комментарий')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('pred_date_rdy', models.DateTimeField(default=datetime.datetime(2019, 5, 23, 9, 32, 41, 505, tzinfo=utc), verbose_name='Предварительная дата готовности')),
            ],
        ),
    ]
