# Generated by Django 2.2 on 2019-05-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pred_date_rdy',
            field=models.DateTimeField(auto_now=True, verbose_name='Предварительная дата готовности'),
        ),
    ]
