# Generated by Django 2.2 on 2019-05-20 11:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pred_date_rdy',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 23, 11, 25, 21, 267, tzinfo=utc), verbose_name='Предварительная дата готовности'),
        ),
    ]
