# Generated by Django 2.2 on 2019-05-12 12:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_pred_date_rdy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pred_date_rdy',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 12, 24, 40, 899005, tzinfo=utc), verbose_name='Предварительная дата готовности'),
        ),
    ]
