# Generated by Django 2.2 on 2019-05-20 11:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190520_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pred_date_rdy',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 23, 11, 30, 29, 298568, tzinfo=utc), verbose_name='Предварительная дата готовности'),
        ),
    ]
