# Generated by Django 2.2 on 2019-05-12 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190512_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pred_date_rdy',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 15, 58, 55, 166026, tzinfo=utc), verbose_name='Предварительная дата готовности'),
        ),
    ]
