# Generated by Django 2.2 on 2019-05-12 17:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190512_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pred_date_rdy',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 17, 23, 4, 836492, tzinfo=utc), verbose_name='Предварительная дата готовности'),
        ),
    ]
