# Generated by Django 2.2 on 2019-05-20 12:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190520_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pred_date_rdy',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 23, 12, 35, 30, 676003, tzinfo=utc), verbose_name='Предварительная дата готовности'),
        ),
    ]
