# Generated by Django 2.2 on 2019-05-15 22:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190512_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pred_date_rdy',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 18, 22, 4, 20, 364299, tzinfo=utc), verbose_name='Предварительная дата готовности'),
        ),
    ]
