# Generated by Django 2.2 on 2019-05-20 16:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190520_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pred_date_rdy',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 23, 16, 59, 51, 129317, tzinfo=utc), verbose_name='Предварительная дата готовности'),
        ),
    ]
