# Generated by Django 2.2 on 2019-05-15 22:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190516_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pred_date_rdy',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 18, 22, 42, 33, 956914, tzinfo=utc), verbose_name='Предварительная дата готовности'),
        ),
    ]
