# Generated by Django 2.2 on 2019-05-23 09:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190520_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pred_date_rdy',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 9, 32, 41, 33009, tzinfo=utc), verbose_name='Предварительная дата готовности'),
        ),
    ]
