# Generated by Django 2.2 on 2019-05-17 09:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20190517_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pred_date_rdy',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 20, 9, 32, 24, 271204, tzinfo=utc), verbose_name='Предварительная дата готовности'),
        ),
    ]
